# docker-compose.yml
version: '3.9'

services:
  app:
    image: "bartoszbugla/test-app:latest"
    ports:
      - "80:3000"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    command: --interval 100