name: deploy-app

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/test-app:latest
      - 
        name: Trigger pull on vm
        run: | 
          echo ${{ secrets.PRIVATE_KEY_BASE64 }} | base64 --decode >> temp.pem
          chmod 400 temp.pem
          sudo ssh -i temp.pem ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} \
          'sudo docker stop $(sudo docker ps -a -q); \
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/test-app:latest; \
          sudo docker run -dp 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/test-app:latest' \
          rm -f temp.pem